iops 2267 alter inspired oxygen
NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN pull request #450
Opened 2023-11-02 12:42 UTC by APageNHS

Initial mistake on profile change - meant to remove value from inspired oxygen, removed it on respirationrate, on fixing it, noticed the vitalsigns loinc/snomed cardinallity I thought i'd already changed wasn't right...

Inspired oxygen changes as agreed on call - remove specimen/bodysite/interpretation, remove fixed values from value

Made active, tweaked descriptions

2023-11-06 08:06 UTC, APageNHS commented on structuredefinitions/UKCore-Observation-VitalSigns-RespirationRate.xml
> -      <min value="1" />
removed by Forge

2023-11-06 08:47 UTC, ryma2fhir requested changes

2023-11-06 08:47 UTC, ryma2fhir commented on structuredefinitions/UKCore-Observation-VitalSigns-RespirationRate.xml
>    <purpose value="To provide implementers with additional support when implementing respiratory rate monitoring and to provide a consistent structure to how the data is presented." />
I thought we were going to add what is in scope & out of scope for this profile. iirc All respiration, so unaided, Oxygen Concentrators, Nasal Cannula, CPAP Devices, Endotracheal Tube, & Mechanical Ventilator are within this scope.

2023-11-06 14:43 UTC, ryma2fhir commented on structuredefinitions/UKCore-Observation-VitalSigns-RespirationRate.xml
> +  <purpose value="To provide implementers with additional support when implementing respiratory rate monitoring and to provide a consistent structure to how the data is presented.&#xD;&#xA;&#xD;&#xA;
'so' isnt a professional word imo. Could we change it to 'including' then removed the 'are within this scope' at the end as it's repeating the start of the sentence

2023-11-07 15:04 UTC, ryma2fhir submitted a review, later dismissed

2023-11-07 15:07 UTC, ryma2fhir approved these changes

2023-11-07 15:36 UTC, merged