Rename Note extension, new r5 backports (STU3)
NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN pull request #473
Opened 2023-11-28 10:14 UTC by APageNHS

Renamed file / id / title / name of the DiagnosticReport Note extension

Added new proxy extensions requested in stu2 ballot comments

2023-12-06 09:53 UTC, ryma2fhir commented on structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
> +  <description value="An extension to support adding additional info supporting info the diagnostic report." />
"support adding additional info supporting info" doesn't make sense. Same in purpose.

2023-12-20 12:13 UTC, ryma2fhir requested changes

2023-12-20 12:13 UTC, ryma2fhir commented on structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-DiagnosticReport" />
needs targeting base

2023-12-20 12:13 UTC, ryma2fhir commented on structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
> +  <status value="draft" />
Still draft?

2023-12-20 12:13 UTC, ryma2fhir commented on structuredefinitions/Extension-UKCore-ObservationTriggeredBy.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Observation" />
needs changing to base

2023-12-20 12:42 UTC, APageNHS commented on structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-DiagnosticReport" />
Done

2023-12-20 12:43 UTC, APageNHS commented on structuredefinitions/Extension-UKCore-ObservationTriggeredBy.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Observation" />
Done

2023-12-20 12:43 UTC, APageNHS commented on structuredefinitions/Extension-UKCore-DiagnosticReportSupportingInfo.xml
> +  <status value="draft" />
Made active

2023-12-20 12:44 UTC, ryma2fhir approved these changes

2023-12-20 12:47 UTC, merged